export const GET_CLIENTES = "GET_CLIENTES";
export const ADD_CLIENTES = "ADD_CLIENTES";
export const UPDATE_CLIENTE = "UPDATE_CLIENTE";
export const REMOVE_CLIENTE = "REMOVE_CLIENTE";
export const SET_ORDENACAO = "SET_ORDENACAO";
export const SET_PESQUISA = "SET_PESQUISA";
export const SET_CLIENTE = "SET_CLIENTE";
